# Generated by Django 4.2.9 on 2024-01-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_ropa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
