# Generated by Django 4.2.9 on 2024-01-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_ropa', '0002_coleccion_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminosLegales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Términos Legales',
            },
        ),
    ]
