# Generated by Django 4.2.9 on 2024-01-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_ropa', '0003_terminoslegales'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='collecciones/'),
        ),
    ]
