# Generated by Django 4.2.9 on 2024-01-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_ropa', '0004_coleccion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
